# Generated by Django 4.0.4 on 2022-05-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('patientname', models.CharField(max_length=20)),
                ('patientpassword', models.CharField(max_length=20)),
                ('patientphone', models.IntegerField()),
            ],
        ),
    ]
